# Generated by Django 3.2.8 on 2021-12-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=12)),
                ('semester', models.IntegerField()),
                ('lecturer', models.CharField(max_length=50)),
                ('uploaded_file', models.FileField(upload_to='store')),
            ],
        ),
    ]
