# Generated by Django 3.2.8 on 2021-12-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitfile',
            name='uploaded_file',
            field=models.FileField(upload_to='main/store'),
        ),
    ]
