# Generated by Django 3.2.8 on 2021-12-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0002_alter_submitfile_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitfile',
            name='uploaded_file',
            field=models.FileField(upload_to=''),
        ),
    ]
