# Generated by Django 4.0.4 on 2022-11-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0003_alter_submitfile_uploaded_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='WrongFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=12)),
                ('semester', models.IntegerField()),
                ('lecturer', models.CharField(max_length=50)),
            ],
        ),
    ]
